spring.application.name=timex

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/timex}
spring.datasource.username=${DB_USERNAME:timex}
spring.datasource.password=${DB_PASSWORD:timex}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
